'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.EntityClient
Namespace Entidades
    
    Partial Public Class rdbmsMibEntities
        Inherits ObjectContext
        Public Const SettingsConnectionString As String = "name=rdbmsMibEntities"
        Public Const ContainerName As String = "rdbmsMibEntities"
    
    #Region "Constructors"
    
        Public Sub New()
            MyBase.New(SettingsConnectionString, ContainerName)
            MyBase.ContextOptions.LazyLoadingEnabled = True
        End Sub
    
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, ContainerName)
            MyBase.ContextOptions.LazyLoadingEnabled = True
        End Sub
    
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, ContainerName)
            MyBase.ContextOptions.LazyLoadingEnabled = True
        End Sub

    #End Region
    #Region "ObjectSet Properties"
    
        Public ReadOnly Property Mibs() As ObjectSet(Of Mibs)
            Get
                If _mibs Is Nothing Then
                    _mibs = CreateObjectSet(Of Mibs)("Mibs")
                End If
                Return _mibs
            End Get
        End Property
        Private _mibs As ObjectSet(Of Mibs)
    
        Public ReadOnly Property Objetos() As ObjectSet(Of Objetos)
            Get
                If _objetos Is Nothing Then
                    _objetos = CreateObjectSet(Of Objetos)("Objetos")
                End If
                Return _objetos
            End Get
        End Property
        Private _objetos As ObjectSet(Of Objetos)

    #End Region
    End Class
End Namespace
