'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Partial Public Class Objetos
    #Region "Primitive Properties"

    Public Overridable Property IdentificadorObjeto As Integer

    Public Overridable Property IdObj As String

    Public Overridable Property Sintaxis As String

    Public Overridable Property Acceso As String

    Public Overridable Property Status As String

    Public Overridable Property Nombre As String

    Public Overridable Property IdentificadorMib As Integer
        Get
            Return _identificadorMib
        End Get
        Set(ByVal value As Integer)
            If Not Equals (_identificadorMib, value) Then
                If Mibs IsNot Nothing AndAlso Not Equals(Mibs.IdentificadorMib, value) Then
                    Mibs = Nothing
                End If
                _identificadorMib = value
            End If
        End Set
    End Property
    Private _identificadorMib As Integer

    Public Overridable Property IdObjPadre As String

    Public Overridable Property Descripcion As String

    #End Region
    #Region "Navigation Properties"

    Public Overridable Property Mibs As Mibs
        Get
            Return _mibs
        End Get
        Set(ByVal value As Mibs)
            If _mibs IsNot value Then
                Dim previousValue As Mibs = _mibs
                _mibs = value
                FixupMibs(previousValue)
            End If
        End Set
    End Property
    Private _mibs As Mibs

    #End Region
    #Region "Association Fixup"

    Private Sub FixupMibs(ByVal previousValue As Mibs)
        If previousValue IsNot Nothing AndAlso previousValue.Objetos.Contains(Me) Then
            previousValue.Objetos.Remove(Me)
        End If
        If Mibs IsNot Nothing Then
            If Not Mibs.Objetos.Contains(Me) Then
                Mibs.Objetos.Add(Me)
            End If
            If Not Equals(IdentificadorMib, Mibs.IdentificadorMib) Then
                IdentificadorMib = Mibs.IdentificadorMib
            End If
        End If
    End Sub

    #End Region
End Class
